title: Portafolio de PATRICIA ROMÁN
author: PATRICIA ROMÁN
email: patricia.roman@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
  Este es mi magnifico sitio web. Aquí encontraras todo lo que buscas y más en referentes a la realización de una página web. 
  ¡No te pierdas nada!

# social links
twitter_username: Patriii1607 # NO incluyas el carácter @ character, ¡o la compilación fallará!
github_username:  PatriciaRomanP # NO incluyas el carácter @ character, ¡o la compilación fallará!

show_excerpts: false # cámbialo a false para eliminar los extractos de la página principal

theme: minima

